### ISSUE TITLE
Helper as an argument to another helper

### ISSUE THREAD

**Issue by mitchHorne** [dalgard/meteor-jade#6]
Not sure if this is possible, but im trying to pass a value inside an each function as an argument to another helper
It looks like :
each thing
   td #{helper #{arg1}}
The argument is a value inside the collection of things and can be shown with
each thing
   td #{arg1}
I've tried passing it to the helper in a number of ways:
# {helper {{arg}}}
# {helper "#{arg}"}
# {helper "{{arg}}"}

{{helper "{{arg}}"}}
etc... with no success, but the helper is executing, just not receiving the passed argument.

**Comment by mickdekkers** [comment]
Not sure if this is correct syntax but have you tried `#{helper arg}` or `{{helper arg}}`?

**Comment by mitchHorne** [comment]
Thank you! Was considering doing it some other way, but #{helper arg} works perfectly in passing another helper to a helper needing an argument. Sorry for the issue create @dalgard. Great work you've done so far.
